<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ujian Pilihan Ganda</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            color: #333;
            text-align: center;
            margin: 0;
            padding: 20px;
            background: url(Kelompok 2.png') center/cover no-repeat;
        }
        h1 { color: #4CAF50; }
        .container {
            margin: 20px auto;
            max-width: 600px;
            background: rgba(255, 255, 255, 0.8);
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
        input, button {
            margin-bottom: 10px;
            padding: 10px;
            width: calc(100% - 22px);
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            background-color: #4CAF50;
            color: white;
            cursor: pointer;
            transition: background 0.3s;
        }
        button:hover { background-color: #45a049; }
        footer { margin-top: 20px; font-size: 12px; color: #777; }
        .error { color: red; }
        .menu {
            position: absolute;
            top: 20px;
            left: 20px;
        }
        .dropdown {
            position: ;
            display: inline-block;
        }
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }
        .dropdown:hover .dropdown-content { display: block; }
    </style>
</head>
<body>

    <!-- Menu Dropdown -->
    <div class="menu dropdown">
        <button class="dropbtn">Menu</button>
        <div class="dropdown-content">
            <button id="resetBtn">Reset</button>
            <button id="helpBtn">Bantuan</button>
            <button id="leaveBtn">Meninggalkan Website</button>
        </div>
    </div>

    <!-- Login Container -->
    <div id="loginContainer" class="container">
        <h1>Login Ujian</h1>
        <input type="text" id="code" placeholder="Kode" required>
        <input type="password" id="password" placeholder="Kata Sandi" required>
        <button id="loginBtn">Masuk</button>
        <div id="errorMessage" class="error"></div>
    </div>

    <!-- User Information Display -->
    <div id="userDisplayContainer" class="container" style="display:none;">
        <h1>Informasi Anda</h1>
        <div id="userInfo"></div>
        <h2>Silakan perbarui jika ada yang salah</h2>
        <input type="text" id="name" placeholder="Nama" required>
        <input type="number" id="absen" placeholder="Nomor Absen (1-32)" min="1" max="32" required>
        <button id="updateUserInfoBtn">Perbarui</button>
        <div id="updateMessage" class="error"></div>
        <button id="startQuizBtn" style="display:none;">Mulai Ujian</button>
    </div>

    <!-- Quiz Container -->
    <div id="quizContainer" class="container" style="display:none;">
        <h1>Ujian Pilihan Ganda</h1>
        <div class="quiz-container" id="quizContent"></div>
        <div>
            <button id="prevBtn" style="display:none;">Sebelumnya</button>
            <button id="nextBtn">Selanjutnya</button>
        </div>
    </div>

    <!-- Result Container -->
    <div id="resultContainer" class="container" style="display:none;">
        <h1>Hasil Ujian</h1>
        <div id="result"></div>
    </div>

    <footer>&copy; Fio F. Yussup, 2024</footer>

    <script>
        // Data Pengguna
        const users = [
            { name: 'John Doe', absen: '10', code: '123', password: '1234' },
            { name: 'Jane Smith', absen: '11', code: '456', password: 'abcd' },
            { name: 'Bob Johnson', absen: '12', code: '789', password: 'qwerty' },
            { name: 'Fio', absen: '12', code: '234', password: '1234'}
        ];

        // Data Pertanyaan
        const questions = [
            {
                question: "1. Manakah yang merupakan contoh kata dengan makna denotasi?",
                options: ["Mawar di taman mekar dengan indah.", "Hatinya penuh mawar cinta.", "Cinta mereka seindah bunga mawar.", "Mawar adalah lambang cinta."],
                answer: 0
            },
            {
                question: "2. Kata \"rumah\" dalam kalimat \"Rumah itu memiliki lima kamar tidur\" memiliki makna:",
                options: ["Denotasi", "Konotasi positif", "Konotasi negatif", "Kiasan"],
                answer: 0
            },
        ];

        let currentQuestionIndex = 0;
        let score = 0;
        let userName = '';
        let userAbsen = '';

        // Fungsi untuk memuat soal ujian
        function loadQuiz() {
            const quizContent = document.getElementById('quizContent');
            const question = questions[currentQuestionIndex];
            const optionsHtml = question.options.map((option, i) => `
                <li class="option">
                    <input type="radio" name="question" value="${i}" id="q${currentQuestionIndex}o${i}">
                    <label for="q${currentQuestionIndex}o${i}">${option}</label>
                </li>
            `).join('');
            quizContent.innerHTML = `
                <h3>${question.question}</h3>
                <ul>${optionsHtml}</ul>
            `;
            document.getElementById('prevBtn').style.display = currentQuestionIndex === 0 ? 'none' : 'inline';
        }

        // Fungsi untuk menyelesaikan ujian dan menampilkan hasil
        function finishQuiz() {
            questions.forEach((q, index) => {
                const selectedOption = document.querySelector(`input[name="question"]:checked`);
                if (selectedOption && parseInt(selectedOption.value) === q.answer) {
                    score++;
                }
            });

            document.getElementById('result').innerHTML = `
                <strong>Nama:</strong> ${userName}<br>
                <strong>Nomor Absen:</strong> ${userAbsen}<br>
                <strong>Skor:</strong> ${score} dari ${questions.length} pertanyaan.<br>
                <strong>Jawaban Pilihan Ganda:</strong>
                <ul>${questions.map((q, index) => {
                    const selectedOption = document.querySelector(`input[name="question"]:checked`);
                    return `<li>${q.question} - ${selectedOption ? q.options[selectedOption.value] : 'Tidak ada jawaban'}</li>`;
                }).join('')}</ul>
            `;

            document.getElementById('resultContainer').style.display = 'block';
            document.getElementById('quizContainer').style.display = 'none';
        }

        // Event Listeners
        document.getElementById('resetBtn').addEventListener('click', () => {
            currentQuestionIndex = 0;
            score = 0;
            document.getElementById('code').value = '';
            document.getElementById('password').value = '';
            document.getElementById('userInfo').innerHTML = '';
            document.getElementById('result').innerHTML = '';
            document.getElementById('resultContainer').style.display = 'none';
            document.getElementById('userDisplayContainer').style.display = 'none';
            document.getElementById('loginContainer').style.display = 'block';
            document.getElementById('quizContainer').style.display = 'none';
        });

        document.getElementById('loginBtn').addEventListener('click', () => {
            const code = document.getElementById('code').value;
            const password = document.getElementById('password').value;

            // Validasi kode dan kata sandi
            const user = users.find(user => user.code === code && user.password === password);
            if (user) {
                userName = user.name;
                userAbsen = user.absen;
                
                // Tampilkan informasi pengguna
                document.getElementById('userInfo').innerHTML = `
                    <strong>Nama:</strong> <span id="displayName">${userName}</span><br>
                    <strong>Nomor Absen:</strong> <span id="displayAbsen">${userAbsen}</span><br>
                `;
                document.getElementById('userDisplayContainer').style.display = 'block';
                document.getElementById('loginContainer').style.display = 'none';
                document.getElementById('startQuizBtn').style.display = 'inline'; // Tampilkan tombol mulai ujian
            } else {
                document.getElementById('errorMessage').innerText = 'Kode atau Kata Sandi salah!';
            }
        });

        document.getElementById('updateUserInfoBtn').addEventListener('click', () => {
            const nameInput = document.getElementById('name').value;
            const absenInput = document.getElementById('absen').value;

            if (nameInput && absenInput) {
                userName = nameInput;
                userAbsen = absenInput;
                document.getElementById('displayName').innerText = userName;
                document.getElementById('displayAbsen').innerText = userAbsen;
                document.getElementById('updateMessage').innerText = 'Informasi berhasil diperbarui!';
                document.getElementById('startQuizBtn').style.display = 'inline'; // Tampilkan tombol mulai ujian
            } else {
                document.getElementById('updateMessage').innerText = 'Silakan isi semua kolom!';
            }
        });

        document.getElementById('startQuizBtn').addEventListener('click', () => {
            document.getElementById('userDisplayContainer').style.display = 'none';
            document.getElementById('quizContainer').style.display = 'block';
            loadQuiz();
        });

        document.getElementById('nextBtn').addEventListener('click', () => {
            const selectedOption = document.querySelector(`input[name="question"]:checked`);
            if (selectedOption) {
                currentQuestionIndex++;
                if (currentQuestionIndex < questions.length) {
                    loadQuiz();
                } else {
                    finishQuiz();
                }
            } else {
                alert('Silakan pilih jawaban sebelum melanjutkan!');
            }
        });

        document.getElementById('prevBtn').addEventListener('click', () => {
            if (currentQuestionIndex > 0) {
                currentQuestionIndex--;
                loadQuiz();
            }
        });

        document.getElementById('helpBtn').addEventListener('click', () => {
            alert('Silakan hubungi pengawas ujian jika Anda membutuhkan bantuan.');
        });

        document.getElementById('leaveBtn').addEventListener('click', () => {
            window.close();
        });
    </script>
</body>
</html>
